{{- if .Values.security.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    environment: {{ .Values.global.environment }}
    {{- if eq .Values.global.environment "production" }}
    pod-security.kubernetes.io/enforce: restricted
    {{- else }}
    pod-security.kubernetes.io/enforce: baseline
    {{- end }}
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
{{- end }}

