{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgresql
spec:
  clusterIP: None   # ⬅️ Headless Service
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgresql
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: voting-app-postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: voting-app-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-app-postgres
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
{{- end }}

