{{- if .Values.result.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: {{ .Values.global.namespace }}
  labels:
    app: result
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
        environment: {{ .Values.global.environment }}
    spec:
      {{- if .Values.security.enabled }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.runAsUser }}
      {{- end }}
      containers:
      - name: result
        image: {{ .Values.images.result }}
        imagePullPolicy: IfNotPresent
        env:
          # من ConfigMap
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: POSTGRES_DB
          # من Secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: voting-app-postgres
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voting-app-postgres
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 4000
        resources:
          {{- toYaml .Values.result.resources | nindent 12 }}
        {{- if .Values.security.enabled }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: {{ .Values.security.runAsUser }}
          capabilities:
            drop:
              - ALL
          {{- if .Values.security.seccompProfile }}
          seccompProfile:
            type: RuntimeDefault
          {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: {{ .Values.global.namespace }}
  labels:
    app: result
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.result.service.type }}
  selector:
    app: result
  ports:
  - port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    {{- if eq .Values.result.service.type "NodePort" }}
    nodePort: {{ .Values.result.service.nodePort }}
    {{- end }}
{{- end }}

