{{- if .Values.vote.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: {{ .Values.global.namespace }}
  labels:
    app: vote
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.vote.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
        environment: {{ .Values.global.environment }}
    spec:
      {{- if .Values.security.enabled }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.runAsUser }}
      {{- end }}
      containers:
      - name: vote
        image: {{ .Values.images.vote }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: OPTION_A
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: OPTION_A
        - name: OPTION_B
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: OPTION_B
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        resources:
          {{- toYaml .Values.vote.resources | nindent 12 }}
        {{- if .Values.security.enabled }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: {{ .Values.security.runAsUser }}
          capabilities:
            drop:
              - ALL
          {{- if .Values.security.seccompProfile }}
          seccompProfile:
            type: RuntimeDefault
          {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: {{ .Values.global.namespace }}
  labels:
    app: vote
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.vote.service.type }}
  selector:
    app: vote
  ports:
  - port: {{ .Values.vote.service.port }}
    targetPort: 80
    {{- if eq .Values.vote.service.type "NodePort" }}
    nodePort: {{ .Values.vote.service.nodePort }}
    {{- end }}
{{- end }}

